// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClientOptions } from '@supabase/supabase-js';
import type { Database } from './types';

type SupabaseEnvKey = 'VITE_SUPABASE_URL' | 'VITE_SUPABASE_PUBLISHABLE_KEY';

const getEnvVar = (key: SupabaseEnvKey): string | undefined => {
  const metaEnv = typeof import.meta !== 'undefined' && import.meta.env ? import.meta.env : undefined;
  if (metaEnv && typeof metaEnv[key] === 'string' && metaEnv[key]) {
    return metaEnv[key];
  }

  if (typeof process !== 'undefined' && process.env && typeof process.env[key] === 'string' && process.env[key]) {
    return process.env[key];
  }

  return undefined;
};

const SUPABASE_URL = getEnvVar('VITE_SUPABASE_URL');
const SUPABASE_PUBLISHABLE_KEY = getEnvVar('VITE_SUPABASE_PUBLISHABLE_KEY');

if (!SUPABASE_URL) {
  throw new Error('Missing environment variable: VITE_SUPABASE_URL');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing environment variable: VITE_SUPABASE_PUBLISHABLE_KEY');
}

const authOptions: SupabaseClientOptions<Database>['auth'] = {
  persistSession: true,
  autoRefreshToken: true,
};

if (typeof window !== 'undefined') {
  authOptions.storage = window.localStorage;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: authOptions,
});